  
name: KHM9Plugin
author: TotallyNotKHM9
main: src\KHM9Plugin\Main
version: "1.0"
description: KHM9Plugin is very useless
api:
- 3.0.0

main: TotallyNotKHM9\KHM9Plugin\Main
commands: []
permissions: []
